### ISSUE TITLE
Market Order 成行

### ISSUE THREAD

**Issue by tz2wang** [techbureau/zaifapi#15]
こんにちは、

あなたのAPIはマーケットオーダーをサポートしていますか？ 以下の書類は、市場指図ではなく、指値注文のみを記載しています。

http://techbureau-api-document.readthedocs.io/ja/latest/trade/2_individual/7_trade.html

どうか教えてください。 ありがとうございました。

**Comment by RossyWhite** [comment]
Hi, @tz2wang 

The document above is correct. We don't provide Market Order API so far.
So if you want to make market order, please do it on website.

Sorry for inconvenience:(

**Comment by tz2wang** [comment]
Hi, 

Thanks very much for your reply.  Do you work for Zaif?

Is there any way to perform market order by API? 

any workaround at all?

Thanks very much for your response.
